"""Lazy policy and blinded-judge adapters for PLUMB.

Importing this package is CPU-safe and does not import or download any model
runtime.  Model frameworks are imported only when a real adapter is invoked.
"""

from .contracts import ExternalPolicyHook, ExternalPolicyProfile, PolicyContractError, PolicyLoadError
from .judge import (
    JudgeAttempt,
    JudgeInputError,
    JudgeInputProvenance,
    JudgeLoadError,
    JudgeReport,
    JudgeRequest,
    JudgeSampleReport,
    JudgeSamplingConfig,
    JudgeSchemaError,
    QwenJudgeProfile,
    QwenRubricJudge,
    ReferenceImage,
    RubricSample,
    parse_rubric_json,
)
from .native import (
    MINIVLA_CONTRACT,
    OCTO_BASE_V1_CONTRACT,
    OCTO_SMALL_V1_CONTRACT,
    OPEN_PI_ZERO_CONTRACT,
    SUSIE_CONTRACT,
    SUSIE_LL_CONTRACT,
    MiniVLAPolicy,
    OctoBaseV1Policy,
    OctoSmallV1Policy,
    OpenPiZeroPolicy,
    SuSIELowLevelPolicy,
    SuSIEPolicy,
)
from .openvla import (
    OPENVLA_BRIDGE_UNNORM_KEY,
    OPENVLA_CONTRACT,
    OPENVLA_MODEL_ID,
    OPENVLA_TRANSFORMERS_VERSION,
    OpenVLAActionReport,
    OpenVLAPolicyAdapter,
    OpenVLAPolicyProfile,
    OpenVLAUnavailableError,
)
from .tasks import BENCHMARK_TASK_REGISTRY, TASK_REGISTRY_HASH, BenchmarkTask, TaskRegistry

__all__ = (
    "ExternalPolicyHook",
    "ExternalPolicyProfile",
    "PolicyContractError",
    "PolicyLoadError",
    "JudgeAttempt",
    "JudgeInputError",
    "JudgeInputProvenance",
    "JudgeLoadError",
    "JudgeReport",
    "JudgeRequest",
    "JudgeSampleReport",
    "JudgeSamplingConfig",
    "JudgeSchemaError",
    "QwenJudgeProfile",
    "QwenRubricJudge",
    "ReferenceImage",
    "RubricSample",
    "parse_rubric_json",
    "MINIVLA_CONTRACT",
    "OCTO_BASE_V1_CONTRACT",
    "OCTO_SMALL_V1_CONTRACT",
    "OPEN_PI_ZERO_CONTRACT",
    "SUSIE_CONTRACT",
    "SUSIE_LL_CONTRACT",
    "MiniVLAPolicy",
    "OctoBaseV1Policy",
    "OctoSmallV1Policy",
    "OpenPiZeroPolicy",
    "SuSIELowLevelPolicy",
    "SuSIEPolicy",
    "OPENVLA_BRIDGE_UNNORM_KEY",
    "OPENVLA_CONTRACT",
    "OPENVLA_MODEL_ID",
    "OPENVLA_TRANSFORMERS_VERSION",
    "OpenVLAActionReport",
    "OpenVLAPolicyAdapter",
    "OpenVLAPolicyProfile",
    "OpenVLAUnavailableError",
    "BENCHMARK_TASK_REGISTRY",
    "TASK_REGISTRY_HASH",
    "BenchmarkTask",
    "TaskRegistry",
)
