"""Lazy policy and blinded-judge adapters for PLUMB.

Importing this package is CPU-safe and does not import or download any model
runtime.  Model frameworks are imported only when a real adapter is invoked.
"""

from .contracts import ExternalPolicyHook, ExternalPolicyProfile, PolicyContractError, PolicyLoadError
from .judge import (
    JudgeAttempt,
    JudgeInputError,
    JudgeInputProvenance,
    JudgeLoadError,
    JudgeReport,
    JudgeRequest,
    JudgeSampleReport,
    JudgeSamplingConfig,
    JudgeSchemaError,
    QwenJudgeProfile,
    QwenRubricJudge,
    ReferenceImage,
    RubricSample,
    parse_rubric_json,
)
from .native import (
    MINIVLA_CONTRACT,
    OCTO_BASE_V1_CONTRACT,
    OCTO_SMALL_V1_CONTRACT,
    OPEN_PI_ZERO_CONTRACT,
    SUSIE_CONTRACT,
    SUSIE_LL_CONTRACT,
    MiniVLAPolicy,
    OctoBaseV1Policy,
    OctoSmallV1Policy,
    OpenPiZeroPolicy,
    SuSIELowLevelPolicy,
    SuSIEPolicy,
)
from .octo import (
    OCTO_ACTION_HORIZON,
    OCTO_AUTOEVAL_NEWER_API_PROFILE_ID,
    OCTO_AUTOEVAL_SERVER_SOURCE,
    OCTO_BASE_CHECKPOINT_STEP,
    OCTO_BASE_MODEL_ID,
    OCTO_BASE_MODEL_REVISION,
    OCTO_JAX_VERSION,
    OCTO_MODEL_SOURCE,
    OCTO_NATIVE_V0_1_PROFILE_ID,
    OCTO_OBSERVATION_HORIZON,
    OCTO_SMALL_CHECKPOINT_STEP,
    OCTO_SMALL_MODEL_ID,
    OCTO_SMALL_MODEL_REVISION,
    OCTO_V1_SOURCE_COMMIT,
    OctoActionReport,
    OctoUnavailableError,
    OctoV1PolicyProfile,
)
from .openvla import (
    OPENVLA_BRIDGE_UNNORM_KEY,
    OPENVLA_CONTRACT,
    OPENVLA_MODEL_ID,
    OPENVLA_TRANSFORMERS_VERSION,
    OpenVLAActionReport,
    OpenVLAPolicyAdapter,
    OpenVLAPolicyProfile,
    OpenVLAUnavailableError,
)
from .tasks import BENCHMARK_TASK_REGISTRY, TASK_REGISTRY_HASH, BenchmarkTask, TaskRegistry
from .minivla import (
    MINIVLA_AUXILIARY_ASSET_BLOCKER, MINIVLA_MODEL_REVISION, MINIVLA_SOURCE_CONTRACT,
    MINIVLA_VQ_LICENSE_BLOCKER, MiniVLAActionReport, MiniVLAPolicyAdapter,
    MiniVLAPolicyProfile, MiniVLAUnavailableError,
)
from .susie import (
    SUSIE_CORRECTED_SENSITIVITY_ARM_ID, SUSIE_LL_CORRECTED_SENSITIVITY_ARM_ID,
    SUSIE_LL_REPLICATION_ARM_ID, SUSIE_REPLICATION_ARM_ID,
    SuSIEActionReport, SuSIELowLevelPolicyAdapter, SuSIEPolicyAdapter,
    SuSIEPolicyProfile, SuSIEUnavailableError,
)
from .openpi import (
    OPENPI_BRIDGE_EEF_QUATERNION_WXYZ, OPENPI_CONTRACT, OpenPiActionReport,
    OpenPiUnavailableError, OpenPiZeroPolicyAdapter, OpenPiZeroPolicyProfile,
)

__all__ = (
    "ExternalPolicyHook",
    "ExternalPolicyProfile",
    "PolicyContractError",
    "PolicyLoadError",
    "JudgeAttempt",
    "JudgeInputError",
    "JudgeInputProvenance",
    "JudgeLoadError",
    "JudgeReport",
    "JudgeRequest",
    "JudgeSampleReport",
    "JudgeSamplingConfig",
    "JudgeSchemaError",
    "QwenJudgeProfile",
    "QwenRubricJudge",
    "ReferenceImage",
    "RubricSample",
    "parse_rubric_json",
    "MINIVLA_CONTRACT",
    "OCTO_BASE_V1_CONTRACT",
    "OCTO_SMALL_V1_CONTRACT",
    "OPEN_PI_ZERO_CONTRACT",
    "SUSIE_CONTRACT",
    "SUSIE_LL_CONTRACT",
    "MiniVLAPolicy",
    "OctoBaseV1Policy",
    "OctoSmallV1Policy",
    "OpenPiZeroPolicy",
    "SuSIELowLevelPolicy",
    "SuSIEPolicy",
    "OCTO_ACTION_HORIZON",
    "OCTO_AUTOEVAL_NEWER_API_PROFILE_ID",
    "OCTO_AUTOEVAL_SERVER_SOURCE",
    "OCTO_BASE_CHECKPOINT_STEP",
    "OCTO_BASE_MODEL_ID",
    "OCTO_BASE_MODEL_REVISION",
    "OCTO_JAX_VERSION",
    "OCTO_MODEL_SOURCE",
    "OCTO_NATIVE_V0_1_PROFILE_ID",
    "OCTO_OBSERVATION_HORIZON",
    "OCTO_SMALL_CHECKPOINT_STEP",
    "OCTO_SMALL_MODEL_ID",
    "OCTO_SMALL_MODEL_REVISION",
    "OCTO_V1_SOURCE_COMMIT",
    "OctoActionReport",
    "OctoUnavailableError",
    "OctoV1PolicyProfile",
    "OPENVLA_BRIDGE_UNNORM_KEY",
    "OPENVLA_CONTRACT",
    "OPENVLA_MODEL_ID",
    "OPENVLA_TRANSFORMERS_VERSION",
    "OpenVLAActionReport",
    "OpenVLAPolicyAdapter",
    "OpenVLAPolicyProfile",
    "OpenVLAUnavailableError",
    "BENCHMARK_TASK_REGISTRY",
    "TASK_REGISTRY_HASH",
    "BenchmarkTask",
    "TaskRegistry",
    "MiniVLAActionReport",
    "MiniVLAPolicyAdapter",
    "MiniVLAPolicyProfile",
    "MiniVLAUnavailableError",
    "SuSIEActionReport",
    "SuSIELowLevelPolicyAdapter",
    "SuSIEPolicyAdapter",
    "SuSIEPolicyProfile",
    "SuSIEUnavailableError",
    "MINIVLA_AUXILIARY_ASSET_BLOCKER",
    "MINIVLA_MODEL_REVISION",
    "MINIVLA_SOURCE_CONTRACT",
    "MINIVLA_VQ_LICENSE_BLOCKER",
    "SUSIE_CORRECTED_SENSITIVITY_ARM_ID",
    "SUSIE_LL_CORRECTED_SENSITIVITY_ARM_ID",
    "SUSIE_LL_REPLICATION_ARM_ID",
    "SUSIE_REPLICATION_ARM_ID",
    "OPENPI_BRIDGE_EEF_QUATERNION_WXYZ",
    "OPENPI_CONTRACT",
    "OpenPiActionReport",
    "OpenPiUnavailableError",
    "OpenPiZeroPolicyAdapter",
    "OpenPiZeroPolicyProfile",
)
