/**
 * What has been checked, by whom, and what has not.
 */
import { useAppData } from "../AppData";
import { ErrorBoundary } from "../components/ErrorBoundary";
import { GatePanel } from "../components/GatePanel";
import { SmokeEvidencePanel } from "../components/SmokeEvidencePanel";
import { CalledShotPanel } from "../components/CalledShotPanel";
import { PageHeader } from "./PageHeader";

export function EvidencePage() {
  const { gates, experiments, calledShot } = useAppData();

  return (
    <div className="page-stack">
      <PageHeader
        title="Validation"
        lede="Checks that tell us whether the model outputs and measurements can be trusted. A working diagnostic is not a validated policy ranking."
      />

      <div className="split-grid">
        <ErrorBoundary region="Smoke evidence">
          <SmokeEvidencePanel experiments={experiments} />
        </ErrorBoundary>
        <ErrorBoundary region="Qualification gates">
          <GatePanel gates={gates} />
        </ErrorBoundary>
      </div>
      <details className="gallery-guide">
        <summary>Research background & published reference numbers</summary>
        <p className="text-pretty">
          The 4% simulator and 92% real-robot figures below come from the cited
          reference study. They are not results generated by this app.
        </p>
        <CalledShotPanel calledShot={calledShot} />
      </details>
    </div>
  );
}
